#!/usr/bin/env python3
"""
GitHub Trending Tracker
Fetches daily GitHub trending repos across AI/ML categories
"""
import requests, json, os
from datetime import datetime, timedelta

TOKEN = os.environ.get("GITHUB_TOKEN", "")
H = {
    "Accept": "application/vnd.github+json",
    "Authorization": f"Bearer {TOKEN}" if TOKEN else "",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "agent-studio/1.0"
}

QUERIES = [
    ("🤖 AI/ML 热门", "topic:artificial-intelligence stars:>100", 8),
    ("🐍 Python 新势力", "language:python stars:>200", 8),
    ("🔥 全站上升项目", "stars:>500", 10),
    ("🆕 近期新项目", "created:>{date}", 6),
]

def search(q, per_page):
    q = q.replace("{date}", (datetime.now() - timedelta(days=14)).strftime("%Y-%m-%d"))
    r = requests.get("https://api.github.com/search/repositories",
        headers=H, params={"q": q, "sort": "stars", "order": "desc", "per_page": per_page}, timeout=15)
    return r.json().get("items", []) if r.status_code == 200 else []

def build_md():
    lines = [f"# 📊 GitHub Trending Report — {datetime.now().strftime('%Y-%m-%d')}", ""]
    for title, q, n in QUERIES:
        repos = search(q, n)
        lines += [f"## {title}", "", "| # | 项目 | ⭐ | 🍴 | 简介 |",
                  "|---|------|----|----|------|"]
        for i, r in enumerate(repos, 1):
            lines.append(f"| {i} | [{r['full_name']}]({r['html_url']}) | {r['stargazers_count']:,} | {r['forks_count']:,} | {(r.get('description') or '—')[:40]} |")
        lines.append("")
    lines.append(f"*Generated by agent-studio · {datetime.now().isoformat()}*")
    return "\n".join(lines)

if __name__ == "__main__":
    print("📡 agent-studio GitHub Trending Tracker")
    md = build_md()
    print(md)
    with open("REPORT.md", "w") as f:
        f.write(md)
    print("\n✅ Report saved to REPORT.md")
