#!/usr/bin/env python3
"""
RSS News Aggregator with AI Categorization
Automatically fetches, categorizes, and summarizes news from multiple RSS feeds.
"""

import feedparser
import json
from datetime import datetime, timedelta
from collections import defaultdict

# Configure your RSS feeds here
RSS_FEEDS = [
    {"name": "Hacker News", "url": "https://hnrss.org/frontpage", "category": "tech"},
    {"name": "TechCrunch", "url": "https://techcrunch.com/feed/", "category": "tech"},
    {"name": "GitHub Blog", "url": "https://github.blog/feed/", "category": "dev"},
    {"name": "The Verge", "url": "https://www.theverge.com/rss/index.xml", "category": "tech"},
    {"name": "AI News", "url": "https://venturebeat.com/category/ai/feed/", "category": "ai"},
]

def fetch_feed(feed_config):
    """Fetch and parse a single RSS feed."""
    try:
        feed = feedparser.parse(feed_config["url"])
        articles = []
        for entry in feed.entries[:10]:  # Latest 10 per feed
            articles.append({
                "title": entry.get("title", ""),
                "link": entry.get("link", ""),
                "published": entry.get("published", ""),
                "summary": entry.get("summary", "")[:200],
                "source": feed_config["name"],
                "category": feed_config["category"],
            })
        return articles
    except Exception as e:
        print(f"Error fetching {feed_config['name']}: {e}")
        return []

def categorize_articles(articles):
    """Group articles by category."""
    categories = defaultdict(list)
    for article in articles:
        categories[article["category"]].append(article)
    return dict(categories)

def generate_report(articles):
    """Generate a daily news digest report."""
    by_category = categorize_articles(articles)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    lines = [f"# 📰 Daily Tech News Digest — {now}\n"]
    lines.append(f"**Total articles:** {len(articles)}\n")
    
    for category, items in by_category.items():
        emoji = {"tech": "💻", "ai": "🤖", "dev": "🔧", "startup": "🚀"}.get(category, "📄")
        lines.append(f"\n## {emoji} {category.upper()} ({len(items)} articles)\n")
        for item in items:
            lines.append(f"- [{item['title']}]({item['link']})")
            lines.append(f"  — {item['source']}")
    
    lines.append("\n---\n*Generated by [Agent Studio](https://github.com/nima54851/agent-studio)*")
    return "\n".join(lines)

def main():
    print(f"Fetching {len(RSS_FEEDS)} RSS feeds...")
    all_articles = []
    for feed_config in RSS_FEEDS:
        articles = fetch_feed(feed_config)
        all_articles.extend(articles)
        print(f"  ✓ {feed_config['name']}: {len(articles)} articles")
    
    report = generate_report(all_articles)
    output_file = f"docs/daily-news-{datetime.now().strftime('%Y-%m-%d')}.md"
    
    with open(output_file, "w") as f:
        f.write(report)
    
    print(f"\n✅ Report saved to {output_file}")
    print(f"   {len(all_articles)} articles from {len(RSS_FEEDS)} sources")
    return report

if __name__ == "__main__":
    main()
