#!/usr/bin/env python3
"""
OpenAPI Spec Generator — AI-powered spec generation from code
Supports: Express, FastAPI, NestJS, raw routes
"""
import argparse, json, re, sys, os
from pathlib import Path

def parse_express_routes(filepath):
    """Extract route definitions from Express app."""
    with open(filepath) as f:
        content = f.read()
    
    routes = []
    patterns = [
        r"(?:app|router)\.(get|post|put|patch|delete)\s*\(\s*['\"]([^'\"]+)['\"]",
        r"@app\.(get|post|put|patch|delete)\s*\(\s*['\"]([^'\"]+)['\"]",
    ]
    for pattern in patterns:
        for match in re.finditer(pattern, content):
            routes.append({
                "method": match.group(1).upper(),
                "path": match.group(2),
                "summary": "",
                "description": ""
            })
    return routes

def parse_fastapi_routes(filepath):
    """Extract route definitions from FastAPI app."""
    with open(filepath) as f:
        content = f.read()
    
    routes = []
    http_methods = ["get", "post", "put", "patch", "delete"]
    for method in http_methods:
        pattern = rf"@app\.{method}\(|@router\.{method}\("
        for match in re.finditer(pattern, content):
            # Try to find path near the decorator
            start = match.start()
            chunk = content[start:start+500]
            path_match = re.search(r"['\"]([^'\"]+)['\"]", chunk[chunk.find('('):])
            if path_match:
                routes.append({
                    "method": method.upper(),
                    "path": path_match.group(1),
                    "summary": "",
                    "description": ""
                })
    return routes

def generate_openapi(routes, title="API", version="1.0.0"):
    spec = {
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": version,
            "description": "Auto-generated by agent-studio OpenAPI Automation"
        },
        "servers": [{"url": "/", "description": "Current API"}],
        "paths": {}
    }
    for route in routes:
        path = route["path"]
        method = route["method"].lower()
        if path not in spec["paths"]:
            spec["paths"][path] = {}
        spec["paths"][path][method] = {
            "summary": route.get("summary", ""),
            "description": route.get("description", ""),
            "responses": {
                "200": {"description": "Successful response"}
            }
        }
    return spec

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--app", required=True, help="Path to main app file")
    parser.add_argument("--output", default="openapi.yaml", help="Output file")
    parser.add_argument("--framework", default="auto", choices=["auto", "express", "fastapi"])
    parser.add_argument("--title", default="My API")
    parser.add_argument("--version", default="1.0.0")
    args = parser.parse_args()

    framework = args.framework
    if framework == "auto":
        if args.app.endswith(".py"):
            framework = "fastapi"
        elif args.app.endswith(".js") or args.app.endswith(".ts"):
            framework = "express"
        else:
            framework = "express"

    if framework == "express":
        routes = parse_express_routes(args.app)
    elif framework == "fastapi":
        routes = parse_fastapi_routes(args.app)
    else:
        print("Unsupported framework")
        sys.exit(1)

    print(f"Found {len(routes)} routes")
    spec = generate_openapi(routes, args.title, args.version)
    
    if args.output.endswith(".json"):
        with open(args.output, "w") as f:
            json.dump(spec, f, indent=2)
    else:
        import yaml
        with open(args.output, "w") as f:
            yaml.dump(spec, f, default_flow_style=False)
    
    print(f"OpenAPI spec written to {args.output}")

if __name__ == "__main__":
    main()
